/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutDottxtRouteImport } from './routes/about[.]txt'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as ForAiRouteImport } from './routes/for-ai'
import { Route as ForAiDottxtRouteImport } from './routes/for-ai[.]txt'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GamesDottxtRouteImport } from './routes/games[.]txt'
import { Route as GatheringRouteImport } from './routes/gathering'
import { Route as GatheringDottxtRouteImport } from './routes/gathering[.]txt'
import { Route as HomeDottxtRouteImport } from './routes/home[.]txt'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LicenseDottxtRouteImport } from './routes/license[.]txt'
import { Route as LlmsDothtmlRouteImport } from './routes/llms[.]html'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PsycheRouteImport } from './routes/psyche'
import { Route as PsycheDottxtRouteImport } from './routes/psyche[.]txt'
import { Route as PuckRouteImport } from './routes/puck'
import { Route as PuckDottxtRouteImport } from './routes/puck[.]txt'
import { Route as RecordsDottxtRouteImport } from './routes/records[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SalonRouteImport } from './routes/salon'
import { Route as SalonDottxtRouteImport } from './routes/salon[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartRouteImport } from './routes/start'
import { Route as StartDottxtRouteImport } from './routes/start[.]txt'
import { Route as ApiImportHistoryRouteImport } from './routes/api/import-history'
import { Route as DataGameDotjsonRouteImport } from './routes/data/game[.]json'
import { Route as DataGameDotsgfRouteImport } from './routes/data/game[.]sgf'
import { Route as GamesSplatRouteImport } from './routes/games/$'
import { Route as GamesIndexDotjsonRouteImport } from './routes/games/index[.]json'
import { Route as GatheringIndexRouteImport } from './routes/gathering/index'
import { Route as GatheringSplatRouteImport } from './routes/gathering/$'
import { Route as GatheringBreakfast002DothtmlRouteImport } from './routes/gathering/breakfast-002[.]html'
import { Route as GatheringBreakfast002DottxtRouteImport } from './routes/gathering/breakfast-002[.]txt'
import { Route as GatheringDinner001IndexDothtmlRouteImport } from './routes/gathering/dinner-001-index[.]html'
import { Route as GatheringDinner001IndexDottxtRouteImport } from './routes/gathering/dinner-001-index[.]txt'
import { Route as GatheringDinner001DothtmlRouteImport } from './routes/gathering/dinner-001[.]html'
import { Route as GatheringDinner001DotjsonRouteImport } from './routes/gathering/dinner-001[.]json'
import { Route as GatheringDinner001DottxtRouteImport } from './routes/gathering/dinner-001[.]txt'
import { Route as GatheringIndexDothtmlRouteImport } from './routes/gathering/index[.]html'
import { Route as GatheringProofTable001DothtmlRouteImport } from './routes/gathering/proof-table-001[.]html'
import { Route as GatheringProofTable001DottxtRouteImport } from './routes/gathering/proof-table-001[.]txt'
import { Route as GoGameIdRouteImport } from './routes/go.$gameId'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as NotesChar123noteIdChar125DottxtRouteImport } from './routes/notes.{$noteId}[.]txt'
import { Route as SalonIndexRouteImport } from './routes/salon/index'
import { Route as SalonSplatRouteImport } from './routes/salon/$'
import { Route as SalonLadderRouteImport } from './routes/salon/ladder'
import { Route as SalonLadderDothtmlRouteImport } from './routes/salon/ladder[.]html'
import { Route as SalonLadderDottxtRouteImport } from './routes/salon/ladder[.]txt'
import { Route as SalonPlainWaterRouteImport } from './routes/salon/plain-water'
import { Route as SalonPlainWaterDothtmlRouteImport } from './routes/salon/plain-water[.]html'
import { Route as SalonPlainWaterDottxtRouteImport } from './routes/salon/plain-water[.]txt'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as ApiGamesGameIdRouteImport } from './routes/api/games/$gameId'
import { Route as ApiGamesCurrentRouteImport } from './routes/api/games/current'
import { Route as GatheringBreakfast002IndexRouteImport } from './routes/gathering/breakfast-002/index'
import { Route as GatheringBreakfast002TableRouteImport } from './routes/gathering/breakfast-002/table'
import { Route as GatheringDinner001PartPartDothtmlRouteImport } from './routes/gathering/dinner-001-part/$part[.]html'
import { Route as GatheringDinner001PartPartDottxtRouteImport } from './routes/gathering/dinner-001-part/$part[.]txt'
import { Route as GatheringDinner001IndexRouteImport } from './routes/gathering/dinner-001/index'
import { Route as GatheringDinner001TableRouteImport } from './routes/gathering/dinner-001/table'
import { Route as GatheringProofTable001IndexRouteImport } from './routes/gathering/proof-table-001/index'
import { Route as GatheringProofTable001RulesRouteImport } from './routes/gathering/proof-table-001/rules'
import { Route as GatheringProofTable001RulesDothtmlRouteImport } from './routes/gathering/proof-table-001/rules[.]html'
import { Route as GatheringProofTable001RulesDottxtRouteImport } from './routes/gathering/proof-table-001/rules[.]txt'
import { Route as GatheringProofTable001TableRouteImport } from './routes/gathering/proof-table-001/table'
import { Route as GatheringProofTable001TableDothtmlRouteImport } from './routes/gathering/proof-table-001/table[.]html'
import { Route as GatheringProofTable001TableDottxtRouteImport } from './routes/gathering/proof-table-001/table[.]txt'
import { Route as GatheringProofTable001TaskRouteImport } from './routes/gathering/proof-table-001/task'
import { Route as GatheringProofTable001TaskDothtmlRouteImport } from './routes/gathering/proof-table-001/task[.]html'
import { Route as GatheringProofTable001TaskDottxtRouteImport } from './routes/gathering/proof-table-001/task[.]txt'
import { Route as ApiGamesGameIdHandoffRouteImport } from './routes/api/games/$gameId.handoff'
import { Route as ApiGamesGameIdJevRouteImport } from './routes/api/games/$gameId.jev'
import { Route as ApiGamesGameIdMovesRouteImport } from './routes/api/games/$gameId.moves'
import { Route as ApiGamesGameIdNotesRouteImport } from './routes/api/games/$gameId.notes'
import { Route as ApiGamesGameIdPacketRouteImport } from './routes/api/games/$gameId.packet'
import { Route as ApiGamesGameIdScorePreviewRouteImport } from './routes/api/games/$gameId.score-preview'
import { Route as ApiGamesGameIdSgfRouteImport } from './routes/api/games/$gameId.sgf'
import { Route as ApiGamesGameIdTextRouteImport } from './routes/api/games/$gameId.text'
import { Route as ApiGatheringBreakfast002LinesRouteImport } from './routes/api/gathering/breakfast-002.lines'
import { Route as ApiGatheringDinner001LinesRouteImport } from './routes/api/gathering/dinner-001.lines'
import { Route as ApiGatheringProofTable001LedgerRouteImport } from './routes/api/gathering/proof-table-001.ledger'
import { Route as ApiGatheringProofTable001LinesRouteImport } from './routes/api/gathering/proof-table-001.lines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDottxtRoute = AboutDottxtRouteImport.update({
  id: '/about.txt',
  path: '/about.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAiRoute = ForAiRouteImport.update({
  id: '/for-ai',
  path: '/for-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAiDottxtRoute = ForAiDottxtRouteImport.update({
  id: '/for-ai.txt',
  path: '/for-ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDottxtRoute = GamesDottxtRouteImport.update({
  id: '/games.txt',
  path: '/games.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringRoute = GatheringRouteImport.update({
  id: '/gathering',
  path: '/gathering',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringDottxtRoute = GatheringDottxtRouteImport.update({
  id: '/gathering.txt',
  path: '/gathering.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDottxtRoute = HomeDottxtRouteImport.update({
  id: '/home.txt',
  path: '/home.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseDottxtRoute = LicenseDottxtRouteImport.update({
  id: '/license.txt',
  path: '/license.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDothtmlRoute = LlmsDothtmlRouteImport.update({
  id: '/llms.html',
  path: '/llms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PsycheRoute = PsycheRouteImport.update({
  id: '/psyche',
  path: '/psyche',
  getParentRoute: () => rootRouteImport,
} as any)
const PsycheDottxtRoute = PsycheDottxtRouteImport.update({
  id: '/psyche.txt',
  path: '/psyche.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PuckRoute = PuckRouteImport.update({
  id: '/puck',
  path: '/puck',
  getParentRoute: () => rootRouteImport,
} as any)
const PuckDottxtRoute = PuckDottxtRouteImport.update({
  id: '/puck.txt',
  path: '/puck.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsDottxtRoute = RecordsDottxtRouteImport.update({
  id: '/records.txt',
  path: '/records.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonDottxtRoute = SalonDottxtRouteImport.update({
  id: '/salon.txt',
  path: '/salon.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDottxtRoute = StartDottxtRouteImport.update({
  id: '/start.txt',
  path: '/start.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportHistoryRoute = ApiImportHistoryRouteImport.update({
  id: '/api/import-history',
  path: '/api/import-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGameDotjsonRoute = DataGameDotjsonRouteImport.update({
  id: '/data/game.json',
  path: '/data/game.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGameDotsgfRoute = DataGameDotsgfRouteImport.update({
  id: '/data/game.sgf',
  path: '/data/game.sgf',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSplatRoute = GamesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => GamesRoute,
} as any)
const GamesIndexDotjsonRoute = GamesIndexDotjsonRouteImport.update({
  id: '/index.json',
  path: '/index.json',
  getParentRoute: () => GamesRoute,
} as any)
const GatheringIndexRoute = GatheringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatheringRoute,
} as any)
const GatheringSplatRoute = GatheringSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => GatheringRoute,
} as any)
const GatheringBreakfast002DothtmlRoute =
  GatheringBreakfast002DothtmlRouteImport.update({
    id: '/breakfast-002.html',
    path: '/breakfast-002.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringBreakfast002DottxtRoute =
  GatheringBreakfast002DottxtRouteImport.update({
    id: '/breakfast-002.txt',
    path: '/breakfast-002.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001IndexDothtmlRoute =
  GatheringDinner001IndexDothtmlRouteImport.update({
    id: '/dinner-001-index.html',
    path: '/dinner-001-index.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001IndexDottxtRoute =
  GatheringDinner001IndexDottxtRouteImport.update({
    id: '/dinner-001-index.txt',
    path: '/dinner-001-index.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001DothtmlRoute =
  GatheringDinner001DothtmlRouteImport.update({
    id: '/dinner-001.html',
    path: '/dinner-001.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001DotjsonRoute =
  GatheringDinner001DotjsonRouteImport.update({
    id: '/dinner-001.json',
    path: '/dinner-001.json',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001DottxtRoute =
  GatheringDinner001DottxtRouteImport.update({
    id: '/dinner-001.txt',
    path: '/dinner-001.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringIndexDothtmlRoute = GatheringIndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => GatheringRoute,
} as any)
const GatheringProofTable001DothtmlRoute =
  GatheringProofTable001DothtmlRouteImport.update({
    id: '/proof-table-001.html',
    path: '/proof-table-001.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001DottxtRoute =
  GatheringProofTable001DottxtRouteImport.update({
    id: '/proof-table-001.txt',
    path: '/proof-table-001.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GoGameIdRoute = GoGameIdRouteImport.update({
  id: '/go/$gameId',
  path: '/go/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesChar123noteIdChar125DottxtRoute =
  NotesChar123noteIdChar125DottxtRouteImport.update({
    id: '/notes/{$noteId}.txt',
    path: '/notes/{$noteId}.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalonIndexRoute = SalonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonRoute,
} as any)
const SalonSplatRoute = SalonSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SalonRoute,
} as any)
const SalonLadderRoute = SalonLadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => SalonRoute,
} as any)
const SalonLadderDothtmlRoute = SalonLadderDothtmlRouteImport.update({
  id: '/ladder.html',
  path: '/ladder.html',
  getParentRoute: () => SalonRoute,
} as any)
const SalonLadderDottxtRoute = SalonLadderDottxtRouteImport.update({
  id: '/ladder.txt',
  path: '/ladder.txt',
  getParentRoute: () => SalonRoute,
} as any)
const SalonPlainWaterRoute = SalonPlainWaterRouteImport.update({
  id: '/plain-water',
  path: '/plain-water',
  getParentRoute: () => SalonRoute,
} as any)
const SalonPlainWaterDothtmlRoute = SalonPlainWaterDothtmlRouteImport.update({
  id: '/plain-water.html',
  path: '/plain-water.html',
  getParentRoute: () => SalonRoute,
} as any)
const SalonPlainWaterDottxtRoute = SalonPlainWaterDottxtRouteImport.update({
  id: '/plain-water.txt',
  path: '/plain-water.txt',
  getParentRoute: () => SalonRoute,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdRoute = ApiGamesGameIdRouteImport.update({
  id: '/api/games/$gameId',
  path: '/api/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCurrentRoute = ApiGamesCurrentRouteImport.update({
  id: '/api/games/current',
  path: '/api/games/current',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringBreakfast002IndexRoute =
  GatheringBreakfast002IndexRouteImport.update({
    id: '/breakfast-002/',
    path: '/breakfast-002/',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringBreakfast002TableRoute =
  GatheringBreakfast002TableRouteImport.update({
    id: '/breakfast-002/table',
    path: '/breakfast-002/table',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001PartPartDothtmlRoute =
  GatheringDinner001PartPartDothtmlRouteImport.update({
    id: '/dinner-001-part/$part.html',
    path: '/dinner-001-part/$part.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001PartPartDottxtRoute =
  GatheringDinner001PartPartDottxtRouteImport.update({
    id: '/dinner-001-part/$part.txt',
    path: '/dinner-001-part/$part.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001IndexRoute = GatheringDinner001IndexRouteImport.update({
  id: '/dinner-001/',
  path: '/dinner-001/',
  getParentRoute: () => GatheringRoute,
} as any)
const GatheringDinner001TableRoute = GatheringDinner001TableRouteImport.update({
  id: '/dinner-001/table',
  path: '/dinner-001/table',
  getParentRoute: () => GatheringRoute,
} as any)
const GatheringProofTable001IndexRoute =
  GatheringProofTable001IndexRouteImport.update({
    id: '/proof-table-001/',
    path: '/proof-table-001/',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001RulesRoute =
  GatheringProofTable001RulesRouteImport.update({
    id: '/proof-table-001/rules',
    path: '/proof-table-001/rules',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001RulesDothtmlRoute =
  GatheringProofTable001RulesDothtmlRouteImport.update({
    id: '/proof-table-001/rules.html',
    path: '/proof-table-001/rules.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001RulesDottxtRoute =
  GatheringProofTable001RulesDottxtRouteImport.update({
    id: '/proof-table-001/rules.txt',
    path: '/proof-table-001/rules.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001TableRoute =
  GatheringProofTable001TableRouteImport.update({
    id: '/proof-table-001/table',
    path: '/proof-table-001/table',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001TableDothtmlRoute =
  GatheringProofTable001TableDothtmlRouteImport.update({
    id: '/proof-table-001/table.html',
    path: '/proof-table-001/table.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001TableDottxtRoute =
  GatheringProofTable001TableDottxtRouteImport.update({
    id: '/proof-table-001/table.txt',
    path: '/proof-table-001/table.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001TaskRoute =
  GatheringProofTable001TaskRouteImport.update({
    id: '/proof-table-001/task',
    path: '/proof-table-001/task',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001TaskDothtmlRoute =
  GatheringProofTable001TaskDothtmlRouteImport.update({
    id: '/proof-table-001/task.html',
    path: '/proof-table-001/task.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringProofTable001TaskDottxtRoute =
  GatheringProofTable001TaskDottxtRouteImport.update({
    id: '/proof-table-001/task.txt',
    path: '/proof-table-001/task.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const ApiGamesGameIdHandoffRoute = ApiGamesGameIdHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdJevRoute = ApiGamesGameIdJevRouteImport.update({
  id: '/jev',
  path: '/jev',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdMovesRoute = ApiGamesGameIdMovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdNotesRoute = ApiGamesGameIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdPacketRoute = ApiGamesGameIdPacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdScorePreviewRoute =
  ApiGamesGameIdScorePreviewRouteImport.update({
    id: '/score-preview',
    path: '/score-preview',
    getParentRoute: () => ApiGamesGameIdRoute,
  } as any)
const ApiGamesGameIdSgfRoute = ApiGamesGameIdSgfRouteImport.update({
  id: '/sgf',
  path: '/sgf',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdTextRoute = ApiGamesGameIdTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGatheringBreakfast002LinesRoute =
  ApiGatheringBreakfast002LinesRouteImport.update({
    id: '/api/gathering/breakfast-002/lines',
    path: '/api/gathering/breakfast-002/lines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGatheringDinner001LinesRoute =
  ApiGatheringDinner001LinesRouteImport.update({
    id: '/api/gathering/dinner-001/lines',
    path: '/api/gathering/dinner-001/lines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGatheringProofTable001LedgerRoute =
  ApiGatheringProofTable001LedgerRouteImport.update({
    id: '/api/gathering/proof-table-001/ledger',
    path: '/api/gathering/proof-table-001/ledger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGatheringProofTable001LinesRoute =
  ApiGatheringProofTable001LinesRouteImport.update({
    id: '/api/gathering/proof-table-001/lines',
    path: '/api/gathering/proof-table-001/lines',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about.txt': typeof AboutDottxtRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/for-ai.txt': typeof ForAiDottxtRoute
  '/games': typeof GamesRouteWithChildren
  '/games.txt': typeof GamesDottxtRoute
  '/gathering': typeof GatheringRouteWithChildren
  '/gathering.txt': typeof GatheringDottxtRoute
  '/home.txt': typeof HomeDottxtRoute
  '/license': typeof LicenseRoute
  '/license.txt': typeof LicenseDottxtRoute
  '/llms.html': typeof LlmsDothtmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/psyche': typeof PsycheRoute
  '/psyche.txt': typeof PsycheDottxtRoute
  '/puck': typeof PuckRoute
  '/puck.txt': typeof PuckDottxtRoute
  '/records.txt': typeof RecordsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salon': typeof SalonRouteWithChildren
  '/salon.txt': typeof SalonDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start.txt': typeof StartDottxtRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/$': typeof GamesSplatRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/gathering/$': typeof GatheringSplatRoute
  '/gathering/breakfast-002.html': typeof GatheringBreakfast002DothtmlRoute
  '/gathering/breakfast-002.txt': typeof GatheringBreakfast002DottxtRoute
  '/gathering/dinner-001-index.html': typeof GatheringDinner001IndexDothtmlRoute
  '/gathering/dinner-001-index.txt': typeof GatheringDinner001IndexDottxtRoute
  '/gathering/dinner-001.html': typeof GatheringDinner001DothtmlRoute
  '/gathering/dinner-001.json': typeof GatheringDinner001DotjsonRoute
  '/gathering/dinner-001.txt': typeof GatheringDinner001DottxtRoute
  '/gathering/index.html': typeof GatheringIndexDothtmlRoute
  '/gathering/proof-table-001.html': typeof GatheringProofTable001DothtmlRoute
  '/gathering/proof-table-001.txt': typeof GatheringProofTable001DottxtRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/{$noteId}.txt': typeof NotesChar123noteIdChar125DottxtRoute
  '/salon/$': typeof SalonSplatRoute
  '/salon/ladder': typeof SalonLadderRoute
  '/salon/ladder.html': typeof SalonLadderDothtmlRoute
  '/salon/ladder.txt': typeof SalonLadderDottxtRoute
  '/salon/plain-water': typeof SalonPlainWaterRoute
  '/salon/plain-water.html': typeof SalonPlainWaterDothtmlRoute
  '/salon/plain-water.txt': typeof SalonPlainWaterDottxtRoute
  '/gathering/': typeof GatheringIndexRoute
  '/salon/': typeof SalonIndexRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/gathering/breakfast-002/table': typeof GatheringBreakfast002TableRoute
  '/gathering/dinner-001-part/$part.html': typeof GatheringDinner001PartPartDothtmlRoute
  '/gathering/dinner-001-part/$part.txt': typeof GatheringDinner001PartPartDottxtRoute
  '/gathering/dinner-001/table': typeof GatheringDinner001TableRoute
  '/gathering/proof-table-001/rules': typeof GatheringProofTable001RulesRoute
  '/gathering/proof-table-001/rules.html': typeof GatheringProofTable001RulesDothtmlRoute
  '/gathering/proof-table-001/rules.txt': typeof GatheringProofTable001RulesDottxtRoute
  '/gathering/proof-table-001/table': typeof GatheringProofTable001TableRoute
  '/gathering/proof-table-001/table.html': typeof GatheringProofTable001TableDothtmlRoute
  '/gathering/proof-table-001/table.txt': typeof GatheringProofTable001TableDottxtRoute
  '/gathering/proof-table-001/task': typeof GatheringProofTable001TaskRoute
  '/gathering/proof-table-001/task.html': typeof GatheringProofTable001TaskDothtmlRoute
  '/gathering/proof-table-001/task.txt': typeof GatheringProofTable001TaskDottxtRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/gathering/breakfast-002/': typeof GatheringBreakfast002IndexRoute
  '/gathering/dinner-001/': typeof GatheringDinner001IndexRoute
  '/gathering/proof-table-001/': typeof GatheringProofTable001IndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
  '/api/games/$gameId/text': typeof ApiGamesGameIdTextRoute
  '/api/gathering/breakfast-002/lines': typeof ApiGatheringBreakfast002LinesRoute
  '/api/gathering/dinner-001/lines': typeof ApiGatheringDinner001LinesRoute
  '/api/gathering/proof-table-001/ledger': typeof ApiGatheringProofTable001LedgerRoute
  '/api/gathering/proof-table-001/lines': typeof ApiGatheringProofTable001LinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about.txt': typeof AboutDottxtRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/for-ai.txt': typeof ForAiDottxtRoute
  '/games': typeof GamesRouteWithChildren
  '/games.txt': typeof GamesDottxtRoute
  '/gathering.txt': typeof GatheringDottxtRoute
  '/home.txt': typeof HomeDottxtRoute
  '/license': typeof LicenseRoute
  '/license.txt': typeof LicenseDottxtRoute
  '/llms.html': typeof LlmsDothtmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/psyche': typeof PsycheRoute
  '/psyche.txt': typeof PsycheDottxtRoute
  '/puck': typeof PuckRoute
  '/puck.txt': typeof PuckDottxtRoute
  '/records.txt': typeof RecordsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salon.txt': typeof SalonDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start.txt': typeof StartDottxtRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/$': typeof GamesSplatRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/gathering/$': typeof GatheringSplatRoute
  '/gathering/breakfast-002.html': typeof GatheringBreakfast002DothtmlRoute
  '/gathering/breakfast-002.txt': typeof GatheringBreakfast002DottxtRoute
  '/gathering/dinner-001-index.html': typeof GatheringDinner001IndexDothtmlRoute
  '/gathering/dinner-001-index.txt': typeof GatheringDinner001IndexDottxtRoute
  '/gathering/dinner-001.html': typeof GatheringDinner001DothtmlRoute
  '/gathering/dinner-001.json': typeof GatheringDinner001DotjsonRoute
  '/gathering/dinner-001.txt': typeof GatheringDinner001DottxtRoute
  '/gathering/index.html': typeof GatheringIndexDothtmlRoute
  '/gathering/proof-table-001.html': typeof GatheringProofTable001DothtmlRoute
  '/gathering/proof-table-001.txt': typeof GatheringProofTable001DottxtRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/{$noteId}.txt': typeof NotesChar123noteIdChar125DottxtRoute
  '/salon/$': typeof SalonSplatRoute
  '/salon/ladder': typeof SalonLadderRoute
  '/salon/ladder.html': typeof SalonLadderDothtmlRoute
  '/salon/ladder.txt': typeof SalonLadderDottxtRoute
  '/salon/plain-water': typeof SalonPlainWaterRoute
  '/salon/plain-water.html': typeof SalonPlainWaterDothtmlRoute
  '/salon/plain-water.txt': typeof SalonPlainWaterDottxtRoute
  '/gathering': typeof GatheringIndexRoute
  '/salon': typeof SalonIndexRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/gathering/breakfast-002/table': typeof GatheringBreakfast002TableRoute
  '/gathering/dinner-001-part/$part.html': typeof GatheringDinner001PartPartDothtmlRoute
  '/gathering/dinner-001-part/$part.txt': typeof GatheringDinner001PartPartDottxtRoute
  '/gathering/dinner-001/table': typeof GatheringDinner001TableRoute
  '/gathering/proof-table-001/rules': typeof GatheringProofTable001RulesRoute
  '/gathering/proof-table-001/rules.html': typeof GatheringProofTable001RulesDothtmlRoute
  '/gathering/proof-table-001/rules.txt': typeof GatheringProofTable001RulesDottxtRoute
  '/gathering/proof-table-001/table': typeof GatheringProofTable001TableRoute
  '/gathering/proof-table-001/table.html': typeof GatheringProofTable001TableDothtmlRoute
  '/gathering/proof-table-001/table.txt': typeof GatheringProofTable001TableDottxtRoute
  '/gathering/proof-table-001/task': typeof GatheringProofTable001TaskRoute
  '/gathering/proof-table-001/task.html': typeof GatheringProofTable001TaskDothtmlRoute
  '/gathering/proof-table-001/task.txt': typeof GatheringProofTable001TaskDottxtRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/gathering/breakfast-002': typeof GatheringBreakfast002IndexRoute
  '/gathering/dinner-001': typeof GatheringDinner001IndexRoute
  '/gathering/proof-table-001': typeof GatheringProofTable001IndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
  '/api/games/$gameId/text': typeof ApiGamesGameIdTextRoute
  '/api/gathering/breakfast-002/lines': typeof ApiGatheringBreakfast002LinesRoute
  '/api/gathering/dinner-001/lines': typeof ApiGatheringDinner001LinesRoute
  '/api/gathering/proof-table-001/ledger': typeof ApiGatheringProofTable001LedgerRoute
  '/api/gathering/proof-table-001/lines': typeof ApiGatheringProofTable001LinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about.txt': typeof AboutDottxtRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/for-ai.txt': typeof ForAiDottxtRoute
  '/games': typeof GamesRouteWithChildren
  '/games.txt': typeof GamesDottxtRoute
  '/gathering': typeof GatheringRouteWithChildren
  '/gathering.txt': typeof GatheringDottxtRoute
  '/home.txt': typeof HomeDottxtRoute
  '/license': typeof LicenseRoute
  '/license.txt': typeof LicenseDottxtRoute
  '/llms.html': typeof LlmsDothtmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/psyche': typeof PsycheRoute
  '/psyche.txt': typeof PsycheDottxtRoute
  '/puck': typeof PuckRoute
  '/puck.txt': typeof PuckDottxtRoute
  '/records.txt': typeof RecordsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salon': typeof SalonRouteWithChildren
  '/salon.txt': typeof SalonDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start.txt': typeof StartDottxtRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/$': typeof GamesSplatRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/gathering/$': typeof GatheringSplatRoute
  '/gathering/breakfast-002.html': typeof GatheringBreakfast002DothtmlRoute
  '/gathering/breakfast-002.txt': typeof GatheringBreakfast002DottxtRoute
  '/gathering/dinner-001-index.html': typeof GatheringDinner001IndexDothtmlRoute
  '/gathering/dinner-001-index.txt': typeof GatheringDinner001IndexDottxtRoute
  '/gathering/dinner-001.html': typeof GatheringDinner001DothtmlRoute
  '/gathering/dinner-001.json': typeof GatheringDinner001DotjsonRoute
  '/gathering/dinner-001.txt': typeof GatheringDinner001DottxtRoute
  '/gathering/index.html': typeof GatheringIndexDothtmlRoute
  '/gathering/proof-table-001.html': typeof GatheringProofTable001DothtmlRoute
  '/gathering/proof-table-001.txt': typeof GatheringProofTable001DottxtRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/{$noteId}.txt': typeof NotesChar123noteIdChar125DottxtRoute
  '/salon/$': typeof SalonSplatRoute
  '/salon/ladder': typeof SalonLadderRoute
  '/salon/ladder.html': typeof SalonLadderDothtmlRoute
  '/salon/ladder.txt': typeof SalonLadderDottxtRoute
  '/salon/plain-water': typeof SalonPlainWaterRoute
  '/salon/plain-water.html': typeof SalonPlainWaterDothtmlRoute
  '/salon/plain-water.txt': typeof SalonPlainWaterDottxtRoute
  '/gathering/': typeof GatheringIndexRoute
  '/salon/': typeof SalonIndexRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/gathering/breakfast-002/table': typeof GatheringBreakfast002TableRoute
  '/gathering/dinner-001-part/$part.html': typeof GatheringDinner001PartPartDothtmlRoute
  '/gathering/dinner-001-part/$part.txt': typeof GatheringDinner001PartPartDottxtRoute
  '/gathering/dinner-001/table': typeof GatheringDinner001TableRoute
  '/gathering/proof-table-001/rules': typeof GatheringProofTable001RulesRoute
  '/gathering/proof-table-001/rules.html': typeof GatheringProofTable001RulesDothtmlRoute
  '/gathering/proof-table-001/rules.txt': typeof GatheringProofTable001RulesDottxtRoute
  '/gathering/proof-table-001/table': typeof GatheringProofTable001TableRoute
  '/gathering/proof-table-001/table.html': typeof GatheringProofTable001TableDothtmlRoute
  '/gathering/proof-table-001/table.txt': typeof GatheringProofTable001TableDottxtRoute
  '/gathering/proof-table-001/task': typeof GatheringProofTable001TaskRoute
  '/gathering/proof-table-001/task.html': typeof GatheringProofTable001TaskDothtmlRoute
  '/gathering/proof-table-001/task.txt': typeof GatheringProofTable001TaskDottxtRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/gathering/breakfast-002/': typeof GatheringBreakfast002IndexRoute
  '/gathering/dinner-001/': typeof GatheringDinner001IndexRoute
  '/gathering/proof-table-001/': typeof GatheringProofTable001IndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
  '/api/games/$gameId/text': typeof ApiGamesGameIdTextRoute
  '/api/gathering/breakfast-002/lines': typeof ApiGatheringBreakfast002LinesRoute
  '/api/gathering/dinner-001/lines': typeof ApiGatheringDinner001LinesRoute
  '/api/gathering/proof-table-001/ledger': typeof ApiGatheringProofTable001LedgerRoute
  '/api/gathering/proof-table-001/lines': typeof ApiGatheringProofTable001LinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about.txt'
    | '/courier'
    | '/for-ai'
    | '/for-ai.txt'
    | '/games'
    | '/games.txt'
    | '/gathering'
    | '/gathering.txt'
    | '/home.txt'
    | '/license'
    | '/license.txt'
    | '/llms.html'
    | '/llms.txt'
    | '/play'
    | '/psyche'
    | '/psyche.txt'
    | '/puck'
    | '/puck.txt'
    | '/records.txt'
    | '/robots.txt'
    | '/salon'
    | '/salon.txt'
    | '/sitemap.xml'
    | '/start'
    | '/start.txt'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/$'
    | '/games/index.json'
    | '/gathering/$'
    | '/gathering/breakfast-002.html'
    | '/gathering/breakfast-002.txt'
    | '/gathering/dinner-001-index.html'
    | '/gathering/dinner-001-index.txt'
    | '/gathering/dinner-001.html'
    | '/gathering/dinner-001.json'
    | '/gathering/dinner-001.txt'
    | '/gathering/index.html'
    | '/gathering/proof-table-001.html'
    | '/gathering/proof-table-001.txt'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/notes/{$noteId}.txt'
    | '/salon/$'
    | '/salon/ladder'
    | '/salon/ladder.html'
    | '/salon/ladder.txt'
    | '/salon/plain-water'
    | '/salon/plain-water.html'
    | '/salon/plain-water.txt'
    | '/gathering/'
    | '/salon/'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/gathering/breakfast-002/table'
    | '/gathering/dinner-001-part/$part.html'
    | '/gathering/dinner-001-part/$part.txt'
    | '/gathering/dinner-001/table'
    | '/gathering/proof-table-001/rules'
    | '/gathering/proof-table-001/rules.html'
    | '/gathering/proof-table-001/rules.txt'
    | '/gathering/proof-table-001/table'
    | '/gathering/proof-table-001/table.html'
    | '/gathering/proof-table-001/table.txt'
    | '/gathering/proof-table-001/task'
    | '/gathering/proof-table-001/task.html'
    | '/gathering/proof-table-001/task.txt'
    | '/api/games/'
    | '/gathering/breakfast-002/'
    | '/gathering/dinner-001/'
    | '/gathering/proof-table-001/'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
    | '/api/games/$gameId/text'
    | '/api/gathering/breakfast-002/lines'
    | '/api/gathering/dinner-001/lines'
    | '/api/gathering/proof-table-001/ledger'
    | '/api/gathering/proof-table-001/lines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about.txt'
    | '/courier'
    | '/for-ai'
    | '/for-ai.txt'
    | '/games'
    | '/games.txt'
    | '/gathering.txt'
    | '/home.txt'
    | '/license'
    | '/license.txt'
    | '/llms.html'
    | '/llms.txt'
    | '/play'
    | '/psyche'
    | '/psyche.txt'
    | '/puck'
    | '/puck.txt'
    | '/records.txt'
    | '/robots.txt'
    | '/salon.txt'
    | '/sitemap.xml'
    | '/start'
    | '/start.txt'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/$'
    | '/games/index.json'
    | '/gathering/$'
    | '/gathering/breakfast-002.html'
    | '/gathering/breakfast-002.txt'
    | '/gathering/dinner-001-index.html'
    | '/gathering/dinner-001-index.txt'
    | '/gathering/dinner-001.html'
    | '/gathering/dinner-001.json'
    | '/gathering/dinner-001.txt'
    | '/gathering/index.html'
    | '/gathering/proof-table-001.html'
    | '/gathering/proof-table-001.txt'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/notes/{$noteId}.txt'
    | '/salon/$'
    | '/salon/ladder'
    | '/salon/ladder.html'
    | '/salon/ladder.txt'
    | '/salon/plain-water'
    | '/salon/plain-water.html'
    | '/salon/plain-water.txt'
    | '/gathering'
    | '/salon'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/gathering/breakfast-002/table'
    | '/gathering/dinner-001-part/$part.html'
    | '/gathering/dinner-001-part/$part.txt'
    | '/gathering/dinner-001/table'
    | '/gathering/proof-table-001/rules'
    | '/gathering/proof-table-001/rules.html'
    | '/gathering/proof-table-001/rules.txt'
    | '/gathering/proof-table-001/table'
    | '/gathering/proof-table-001/table.html'
    | '/gathering/proof-table-001/table.txt'
    | '/gathering/proof-table-001/task'
    | '/gathering/proof-table-001/task.html'
    | '/gathering/proof-table-001/task.txt'
    | '/api/games'
    | '/gathering/breakfast-002'
    | '/gathering/dinner-001'
    | '/gathering/proof-table-001'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
    | '/api/games/$gameId/text'
    | '/api/gathering/breakfast-002/lines'
    | '/api/gathering/dinner-001/lines'
    | '/api/gathering/proof-table-001/ledger'
    | '/api/gathering/proof-table-001/lines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about.txt'
    | '/courier'
    | '/for-ai'
    | '/for-ai.txt'
    | '/games'
    | '/games.txt'
    | '/gathering'
    | '/gathering.txt'
    | '/home.txt'
    | '/license'
    | '/license.txt'
    | '/llms.html'
    | '/llms.txt'
    | '/play'
    | '/psyche'
    | '/psyche.txt'
    | '/puck'
    | '/puck.txt'
    | '/records.txt'
    | '/robots.txt'
    | '/salon'
    | '/salon.txt'
    | '/sitemap.xml'
    | '/start'
    | '/start.txt'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/$'
    | '/games/index.json'
    | '/gathering/$'
    | '/gathering/breakfast-002.html'
    | '/gathering/breakfast-002.txt'
    | '/gathering/dinner-001-index.html'
    | '/gathering/dinner-001-index.txt'
    | '/gathering/dinner-001.html'
    | '/gathering/dinner-001.json'
    | '/gathering/dinner-001.txt'
    | '/gathering/index.html'
    | '/gathering/proof-table-001.html'
    | '/gathering/proof-table-001.txt'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/notes/{$noteId}.txt'
    | '/salon/$'
    | '/salon/ladder'
    | '/salon/ladder.html'
    | '/salon/ladder.txt'
    | '/salon/plain-water'
    | '/salon/plain-water.html'
    | '/salon/plain-water.txt'
    | '/gathering/'
    | '/salon/'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/gathering/breakfast-002/table'
    | '/gathering/dinner-001-part/$part.html'
    | '/gathering/dinner-001-part/$part.txt'
    | '/gathering/dinner-001/table'
    | '/gathering/proof-table-001/rules'
    | '/gathering/proof-table-001/rules.html'
    | '/gathering/proof-table-001/rules.txt'
    | '/gathering/proof-table-001/table'
    | '/gathering/proof-table-001/table.html'
    | '/gathering/proof-table-001/table.txt'
    | '/gathering/proof-table-001/task'
    | '/gathering/proof-table-001/task.html'
    | '/gathering/proof-table-001/task.txt'
    | '/api/games/'
    | '/gathering/breakfast-002/'
    | '/gathering/dinner-001/'
    | '/gathering/proof-table-001/'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
    | '/api/games/$gameId/text'
    | '/api/gathering/breakfast-002/lines'
    | '/api/gathering/dinner-001/lines'
    | '/api/gathering/proof-table-001/ledger'
    | '/api/gathering/proof-table-001/lines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutDottxtRoute: typeof AboutDottxtRoute
  CourierRoute: typeof CourierRoute
  ForAiRoute: typeof ForAiRoute
  ForAiDottxtRoute: typeof ForAiDottxtRoute
  GamesRoute: typeof GamesRouteWithChildren
  GamesDottxtRoute: typeof GamesDottxtRoute
  GatheringRoute: typeof GatheringRouteWithChildren
  GatheringDottxtRoute: typeof GatheringDottxtRoute
  HomeDottxtRoute: typeof HomeDottxtRoute
  LicenseRoute: typeof LicenseRoute
  LicenseDottxtRoute: typeof LicenseDottxtRoute
  LlmsDothtmlRoute: typeof LlmsDothtmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PlayRoute: typeof PlayRoute
  PsycheRoute: typeof PsycheRoute
  PsycheDottxtRoute: typeof PsycheDottxtRoute
  PuckRoute: typeof PuckRoute
  PuckDottxtRoute: typeof PuckDottxtRoute
  RecordsDottxtRoute: typeof RecordsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SalonRoute: typeof SalonRouteWithChildren
  SalonDottxtRoute: typeof SalonDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  StartDottxtRoute: typeof StartDottxtRoute
  ApiImportHistoryRoute: typeof ApiImportHistoryRoute
  DataGameDotjsonRoute: typeof DataGameDotjsonRoute
  DataGameDotsgfRoute: typeof DataGameDotsgfRoute
  GoGameIdRoute: typeof GoGameIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesChar123noteIdChar125DottxtRoute: typeof NotesChar123noteIdChar125DottxtRoute
  ApiGamesGameIdRoute: typeof ApiGamesGameIdRouteWithChildren
  ApiGamesCurrentRoute: typeof ApiGamesCurrentRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
  ApiGatheringBreakfast002LinesRoute: typeof ApiGatheringBreakfast002LinesRoute
  ApiGatheringDinner001LinesRoute: typeof ApiGatheringDinner001LinesRoute
  ApiGatheringProofTable001LedgerRoute: typeof ApiGatheringProofTable001LedgerRoute
  ApiGatheringProofTable001LinesRoute: typeof ApiGatheringProofTable001LinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about.txt': {
      id: '/about.txt'
      path: '/about.txt'
      fullPath: '/about.txt'
      preLoaderRoute: typeof AboutDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-ai': {
      id: '/for-ai'
      path: '/for-ai'
      fullPath: '/for-ai'
      preLoaderRoute: typeof ForAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-ai.txt': {
      id: '/for-ai.txt'
      path: '/for-ai.txt'
      fullPath: '/for-ai.txt'
      preLoaderRoute: typeof ForAiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games.txt': {
      id: '/games.txt'
      path: '/games.txt'
      fullPath: '/games.txt'
      preLoaderRoute: typeof GamesDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gathering': {
      id: '/gathering'
      path: '/gathering'
      fullPath: '/gathering'
      preLoaderRoute: typeof GatheringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gathering.txt': {
      id: '/gathering.txt'
      path: '/gathering.txt'
      fullPath: '/gathering.txt'
      preLoaderRoute: typeof GatheringDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home.txt': {
      id: '/home.txt'
      path: '/home.txt'
      fullPath: '/home.txt'
      preLoaderRoute: typeof HomeDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license.txt': {
      id: '/license.txt'
      path: '/license.txt'
      fullPath: '/license.txt'
      preLoaderRoute: typeof LicenseDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.html': {
      id: '/llms.html'
      path: '/llms.html'
      fullPath: '/llms.html'
      preLoaderRoute: typeof LlmsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psyche': {
      id: '/psyche'
      path: '/psyche'
      fullPath: '/psyche'
      preLoaderRoute: typeof PsycheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psyche.txt': {
      id: '/psyche.txt'
      path: '/psyche.txt'
      fullPath: '/psyche.txt'
      preLoaderRoute: typeof PsycheDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puck': {
      id: '/puck'
      path: '/puck'
      fullPath: '/puck'
      preLoaderRoute: typeof PuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puck.txt': {
      id: '/puck.txt'
      path: '/puck.txt'
      fullPath: '/puck.txt'
      preLoaderRoute: typeof PuckDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records.txt': {
      id: '/records.txt'
      path: '/records.txt'
      fullPath: '/records.txt'
      preLoaderRoute: typeof RecordsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon.txt': {
      id: '/salon.txt'
      path: '/salon.txt'
      fullPath: '/salon.txt'
      preLoaderRoute: typeof SalonDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start.txt': {
      id: '/start.txt'
      path: '/start.txt'
      fullPath: '/start.txt'
      preLoaderRoute: typeof StartDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-history': {
      id: '/api/import-history'
      path: '/api/import-history'
      fullPath: '/api/import-history'
      preLoaderRoute: typeof ApiImportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/game.json': {
      id: '/data/game.json'
      path: '/data/game.json'
      fullPath: '/data/game.json'
      preLoaderRoute: typeof DataGameDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/game.sgf': {
      id: '/data/game.sgf'
      path: '/data/game.sgf'
      fullPath: '/data/game.sgf'
      preLoaderRoute: typeof DataGameDotsgfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$': {
      id: '/games/$'
      path: '/$'
      fullPath: '/games/$'
      preLoaderRoute: typeof GamesSplatRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/index.json': {
      id: '/games/index.json'
      path: '/index.json'
      fullPath: '/games/index.json'
      preLoaderRoute: typeof GamesIndexDotjsonRouteImport
      parentRoute: typeof GamesRoute
    }
    '/gathering/': {
      id: '/gathering/'
      path: '/'
      fullPath: '/gathering/'
      preLoaderRoute: typeof GatheringIndexRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/$': {
      id: '/gathering/$'
      path: '/$'
      fullPath: '/gathering/$'
      preLoaderRoute: typeof GatheringSplatRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/breakfast-002.html': {
      id: '/gathering/breakfast-002.html'
      path: '/breakfast-002.html'
      fullPath: '/gathering/breakfast-002.html'
      preLoaderRoute: typeof GatheringBreakfast002DothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/breakfast-002.txt': {
      id: '/gathering/breakfast-002.txt'
      path: '/breakfast-002.txt'
      fullPath: '/gathering/breakfast-002.txt'
      preLoaderRoute: typeof GatheringBreakfast002DottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001-index.html': {
      id: '/gathering/dinner-001-index.html'
      path: '/dinner-001-index.html'
      fullPath: '/gathering/dinner-001-index.html'
      preLoaderRoute: typeof GatheringDinner001IndexDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001-index.txt': {
      id: '/gathering/dinner-001-index.txt'
      path: '/dinner-001-index.txt'
      fullPath: '/gathering/dinner-001-index.txt'
      preLoaderRoute: typeof GatheringDinner001IndexDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001.html': {
      id: '/gathering/dinner-001.html'
      path: '/dinner-001.html'
      fullPath: '/gathering/dinner-001.html'
      preLoaderRoute: typeof GatheringDinner001DothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001.json': {
      id: '/gathering/dinner-001.json'
      path: '/dinner-001.json'
      fullPath: '/gathering/dinner-001.json'
      preLoaderRoute: typeof GatheringDinner001DotjsonRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001.txt': {
      id: '/gathering/dinner-001.txt'
      path: '/dinner-001.txt'
      fullPath: '/gathering/dinner-001.txt'
      preLoaderRoute: typeof GatheringDinner001DottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/index.html': {
      id: '/gathering/index.html'
      path: '/index.html'
      fullPath: '/gathering/index.html'
      preLoaderRoute: typeof GatheringIndexDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001.html': {
      id: '/gathering/proof-table-001.html'
      path: '/proof-table-001.html'
      fullPath: '/gathering/proof-table-001.html'
      preLoaderRoute: typeof GatheringProofTable001DothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001.txt': {
      id: '/gathering/proof-table-001.txt'
      path: '/proof-table-001.txt'
      fullPath: '/gathering/proof-table-001.txt'
      preLoaderRoute: typeof GatheringProofTable001DottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/go/$gameId': {
      id: '/go/$gameId'
      path: '/go/$gameId'
      fullPath: '/go/$gameId'
      preLoaderRoute: typeof GoGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/{$noteId}.txt': {
      id: '/notes/{$noteId}.txt'
      path: '/notes/{$noteId}.txt'
      fullPath: '/notes/{$noteId}.txt'
      preLoaderRoute: typeof NotesChar123noteIdChar125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/': {
      id: '/salon/'
      path: '/'
      fullPath: '/salon/'
      preLoaderRoute: typeof SalonIndexRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/$': {
      id: '/salon/$'
      path: '/$'
      fullPath: '/salon/$'
      preLoaderRoute: typeof SalonSplatRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/ladder': {
      id: '/salon/ladder'
      path: '/ladder'
      fullPath: '/salon/ladder'
      preLoaderRoute: typeof SalonLadderRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/ladder.html': {
      id: '/salon/ladder.html'
      path: '/ladder.html'
      fullPath: '/salon/ladder.html'
      preLoaderRoute: typeof SalonLadderDothtmlRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/ladder.txt': {
      id: '/salon/ladder.txt'
      path: '/ladder.txt'
      fullPath: '/salon/ladder.txt'
      preLoaderRoute: typeof SalonLadderDottxtRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/plain-water': {
      id: '/salon/plain-water'
      path: '/plain-water'
      fullPath: '/salon/plain-water'
      preLoaderRoute: typeof SalonPlainWaterRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/plain-water.html': {
      id: '/salon/plain-water.html'
      path: '/plain-water.html'
      fullPath: '/salon/plain-water.html'
      preLoaderRoute: typeof SalonPlainWaterDothtmlRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/plain-water.txt': {
      id: '/salon/plain-water.txt'
      path: '/plain-water.txt'
      fullPath: '/salon/plain-water.txt'
      preLoaderRoute: typeof SalonPlainWaterDottxtRouteImport
      parentRoute: typeof SalonRoute
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games/'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId': {
      id: '/api/games/$gameId'
      path: '/api/games/$gameId'
      fullPath: '/api/games/$gameId'
      preLoaderRoute: typeof ApiGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/current': {
      id: '/api/games/current'
      path: '/api/games/current'
      fullPath: '/api/games/current'
      preLoaderRoute: typeof ApiGamesCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gathering/breakfast-002/': {
      id: '/gathering/breakfast-002/'
      path: '/breakfast-002'
      fullPath: '/gathering/breakfast-002/'
      preLoaderRoute: typeof GatheringBreakfast002IndexRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/breakfast-002/table': {
      id: '/gathering/breakfast-002/table'
      path: '/breakfast-002/table'
      fullPath: '/gathering/breakfast-002/table'
      preLoaderRoute: typeof GatheringBreakfast002TableRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001-part/$part.html': {
      id: '/gathering/dinner-001-part/$part.html'
      path: '/dinner-001-part/$part.html'
      fullPath: '/gathering/dinner-001-part/$part.html'
      preLoaderRoute: typeof GatheringDinner001PartPartDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001-part/$part.txt': {
      id: '/gathering/dinner-001-part/$part.txt'
      path: '/dinner-001-part/$part.txt'
      fullPath: '/gathering/dinner-001-part/$part.txt'
      preLoaderRoute: typeof GatheringDinner001PartPartDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001/': {
      id: '/gathering/dinner-001/'
      path: '/dinner-001'
      fullPath: '/gathering/dinner-001/'
      preLoaderRoute: typeof GatheringDinner001IndexRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001/table': {
      id: '/gathering/dinner-001/table'
      path: '/dinner-001/table'
      fullPath: '/gathering/dinner-001/table'
      preLoaderRoute: typeof GatheringDinner001TableRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/': {
      id: '/gathering/proof-table-001/'
      path: '/proof-table-001'
      fullPath: '/gathering/proof-table-001/'
      preLoaderRoute: typeof GatheringProofTable001IndexRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/rules': {
      id: '/gathering/proof-table-001/rules'
      path: '/proof-table-001/rules'
      fullPath: '/gathering/proof-table-001/rules'
      preLoaderRoute: typeof GatheringProofTable001RulesRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/rules.html': {
      id: '/gathering/proof-table-001/rules.html'
      path: '/proof-table-001/rules.html'
      fullPath: '/gathering/proof-table-001/rules.html'
      preLoaderRoute: typeof GatheringProofTable001RulesDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/rules.txt': {
      id: '/gathering/proof-table-001/rules.txt'
      path: '/proof-table-001/rules.txt'
      fullPath: '/gathering/proof-table-001/rules.txt'
      preLoaderRoute: typeof GatheringProofTable001RulesDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/table': {
      id: '/gathering/proof-table-001/table'
      path: '/proof-table-001/table'
      fullPath: '/gathering/proof-table-001/table'
      preLoaderRoute: typeof GatheringProofTable001TableRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/table.html': {
      id: '/gathering/proof-table-001/table.html'
      path: '/proof-table-001/table.html'
      fullPath: '/gathering/proof-table-001/table.html'
      preLoaderRoute: typeof GatheringProofTable001TableDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/table.txt': {
      id: '/gathering/proof-table-001/table.txt'
      path: '/proof-table-001/table.txt'
      fullPath: '/gathering/proof-table-001/table.txt'
      preLoaderRoute: typeof GatheringProofTable001TableDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/task': {
      id: '/gathering/proof-table-001/task'
      path: '/proof-table-001/task'
      fullPath: '/gathering/proof-table-001/task'
      preLoaderRoute: typeof GatheringProofTable001TaskRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/task.html': {
      id: '/gathering/proof-table-001/task.html'
      path: '/proof-table-001/task.html'
      fullPath: '/gathering/proof-table-001/task.html'
      preLoaderRoute: typeof GatheringProofTable001TaskDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/proof-table-001/task.txt': {
      id: '/gathering/proof-table-001/task.txt'
      path: '/proof-table-001/task.txt'
      fullPath: '/gathering/proof-table-001/task.txt'
      preLoaderRoute: typeof GatheringProofTable001TaskDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/api/games/$gameId/handoff': {
      id: '/api/games/$gameId/handoff'
      path: '/handoff'
      fullPath: '/api/games/$gameId/handoff'
      preLoaderRoute: typeof ApiGamesGameIdHandoffRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/jev': {
      id: '/api/games/$gameId/jev'
      path: '/jev'
      fullPath: '/api/games/$gameId/jev'
      preLoaderRoute: typeof ApiGamesGameIdJevRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/moves': {
      id: '/api/games/$gameId/moves'
      path: '/moves'
      fullPath: '/api/games/$gameId/moves'
      preLoaderRoute: typeof ApiGamesGameIdMovesRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/notes': {
      id: '/api/games/$gameId/notes'
      path: '/notes'
      fullPath: '/api/games/$gameId/notes'
      preLoaderRoute: typeof ApiGamesGameIdNotesRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/packet': {
      id: '/api/games/$gameId/packet'
      path: '/packet'
      fullPath: '/api/games/$gameId/packet'
      preLoaderRoute: typeof ApiGamesGameIdPacketRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/score-preview': {
      id: '/api/games/$gameId/score-preview'
      path: '/score-preview'
      fullPath: '/api/games/$gameId/score-preview'
      preLoaderRoute: typeof ApiGamesGameIdScorePreviewRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/sgf': {
      id: '/api/games/$gameId/sgf'
      path: '/sgf'
      fullPath: '/api/games/$gameId/sgf'
      preLoaderRoute: typeof ApiGamesGameIdSgfRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/text': {
      id: '/api/games/$gameId/text'
      path: '/text'
      fullPath: '/api/games/$gameId/text'
      preLoaderRoute: typeof ApiGamesGameIdTextRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/gathering/breakfast-002/lines': {
      id: '/api/gathering/breakfast-002/lines'
      path: '/api/gathering/breakfast-002/lines'
      fullPath: '/api/gathering/breakfast-002/lines'
      preLoaderRoute: typeof ApiGatheringBreakfast002LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gathering/dinner-001/lines': {
      id: '/api/gathering/dinner-001/lines'
      path: '/api/gathering/dinner-001/lines'
      fullPath: '/api/gathering/dinner-001/lines'
      preLoaderRoute: typeof ApiGatheringDinner001LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gathering/proof-table-001/ledger': {
      id: '/api/gathering/proof-table-001/ledger'
      path: '/api/gathering/proof-table-001/ledger'
      fullPath: '/api/gathering/proof-table-001/ledger'
      preLoaderRoute: typeof ApiGatheringProofTable001LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gathering/proof-table-001/lines': {
      id: '/api/gathering/proof-table-001/lines'
      path: '/api/gathering/proof-table-001/lines'
      fullPath: '/api/gathering/proof-table-001/lines'
      preLoaderRoute: typeof ApiGatheringProofTable001LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesSplatRoute: typeof GamesSplatRoute
  GamesIndexDotjsonRoute: typeof GamesIndexDotjsonRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesSplatRoute: GamesSplatRoute,
  GamesIndexDotjsonRoute: GamesIndexDotjsonRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface GatheringRouteChildren {
  GatheringSplatRoute: typeof GatheringSplatRoute
  GatheringBreakfast002DothtmlRoute: typeof GatheringBreakfast002DothtmlRoute
  GatheringBreakfast002DottxtRoute: typeof GatheringBreakfast002DottxtRoute
  GatheringDinner001IndexDothtmlRoute: typeof GatheringDinner001IndexDothtmlRoute
  GatheringDinner001IndexDottxtRoute: typeof GatheringDinner001IndexDottxtRoute
  GatheringDinner001DothtmlRoute: typeof GatheringDinner001DothtmlRoute
  GatheringDinner001DotjsonRoute: typeof GatheringDinner001DotjsonRoute
  GatheringDinner001DottxtRoute: typeof GatheringDinner001DottxtRoute
  GatheringIndexDothtmlRoute: typeof GatheringIndexDothtmlRoute
  GatheringProofTable001DothtmlRoute: typeof GatheringProofTable001DothtmlRoute
  GatheringProofTable001DottxtRoute: typeof GatheringProofTable001DottxtRoute
  GatheringIndexRoute: typeof GatheringIndexRoute
  GatheringBreakfast002TableRoute: typeof GatheringBreakfast002TableRoute
  GatheringDinner001PartPartDothtmlRoute: typeof GatheringDinner001PartPartDothtmlRoute
  GatheringDinner001PartPartDottxtRoute: typeof GatheringDinner001PartPartDottxtRoute
  GatheringDinner001TableRoute: typeof GatheringDinner001TableRoute
  GatheringProofTable001RulesRoute: typeof GatheringProofTable001RulesRoute
  GatheringProofTable001RulesDothtmlRoute: typeof GatheringProofTable001RulesDothtmlRoute
  GatheringProofTable001RulesDottxtRoute: typeof GatheringProofTable001RulesDottxtRoute
  GatheringProofTable001TableRoute: typeof GatheringProofTable001TableRoute
  GatheringProofTable001TableDothtmlRoute: typeof GatheringProofTable001TableDothtmlRoute
  GatheringProofTable001TableDottxtRoute: typeof GatheringProofTable001TableDottxtRoute
  GatheringProofTable001TaskRoute: typeof GatheringProofTable001TaskRoute
  GatheringProofTable001TaskDothtmlRoute: typeof GatheringProofTable001TaskDothtmlRoute
  GatheringProofTable001TaskDottxtRoute: typeof GatheringProofTable001TaskDottxtRoute
  GatheringBreakfast002IndexRoute: typeof GatheringBreakfast002IndexRoute
  GatheringDinner001IndexRoute: typeof GatheringDinner001IndexRoute
  GatheringProofTable001IndexRoute: typeof GatheringProofTable001IndexRoute
}

const GatheringRouteChildren: GatheringRouteChildren = {
  GatheringSplatRoute: GatheringSplatRoute,
  GatheringBreakfast002DothtmlRoute: GatheringBreakfast002DothtmlRoute,
  GatheringBreakfast002DottxtRoute: GatheringBreakfast002DottxtRoute,
  GatheringDinner001IndexDothtmlRoute: GatheringDinner001IndexDothtmlRoute,
  GatheringDinner001IndexDottxtRoute: GatheringDinner001IndexDottxtRoute,
  GatheringDinner001DothtmlRoute: GatheringDinner001DothtmlRoute,
  GatheringDinner001DotjsonRoute: GatheringDinner001DotjsonRoute,
  GatheringDinner001DottxtRoute: GatheringDinner001DottxtRoute,
  GatheringIndexDothtmlRoute: GatheringIndexDothtmlRoute,
  GatheringProofTable001DothtmlRoute: GatheringProofTable001DothtmlRoute,
  GatheringProofTable001DottxtRoute: GatheringProofTable001DottxtRoute,
  GatheringIndexRoute: GatheringIndexRoute,
  GatheringBreakfast002TableRoute: GatheringBreakfast002TableRoute,
  GatheringDinner001PartPartDothtmlRoute:
    GatheringDinner001PartPartDothtmlRoute,
  GatheringDinner001PartPartDottxtRoute: GatheringDinner001PartPartDottxtRoute,
  GatheringDinner001TableRoute: GatheringDinner001TableRoute,
  GatheringProofTable001RulesRoute: GatheringProofTable001RulesRoute,
  GatheringProofTable001RulesDothtmlRoute:
    GatheringProofTable001RulesDothtmlRoute,
  GatheringProofTable001RulesDottxtRoute:
    GatheringProofTable001RulesDottxtRoute,
  GatheringProofTable001TableRoute: GatheringProofTable001TableRoute,
  GatheringProofTable001TableDothtmlRoute:
    GatheringProofTable001TableDothtmlRoute,
  GatheringProofTable001TableDottxtRoute:
    GatheringProofTable001TableDottxtRoute,
  GatheringProofTable001TaskRoute: GatheringProofTable001TaskRoute,
  GatheringProofTable001TaskDothtmlRoute:
    GatheringProofTable001TaskDothtmlRoute,
  GatheringProofTable001TaskDottxtRoute: GatheringProofTable001TaskDottxtRoute,
  GatheringBreakfast002IndexRoute: GatheringBreakfast002IndexRoute,
  GatheringDinner001IndexRoute: GatheringDinner001IndexRoute,
  GatheringProofTable001IndexRoute: GatheringProofTable001IndexRoute,
}

const GatheringRouteWithChildren = GatheringRoute._addFileChildren(
  GatheringRouteChildren,
)

interface SalonRouteChildren {
  SalonSplatRoute: typeof SalonSplatRoute
  SalonLadderRoute: typeof SalonLadderRoute
  SalonLadderDothtmlRoute: typeof SalonLadderDothtmlRoute
  SalonLadderDottxtRoute: typeof SalonLadderDottxtRoute
  SalonPlainWaterRoute: typeof SalonPlainWaterRoute
  SalonPlainWaterDothtmlRoute: typeof SalonPlainWaterDothtmlRoute
  SalonPlainWaterDottxtRoute: typeof SalonPlainWaterDottxtRoute
  SalonIndexRoute: typeof SalonIndexRoute
}

const SalonRouteChildren: SalonRouteChildren = {
  SalonSplatRoute: SalonSplatRoute,
  SalonLadderRoute: SalonLadderRoute,
  SalonLadderDothtmlRoute: SalonLadderDothtmlRoute,
  SalonLadderDottxtRoute: SalonLadderDottxtRoute,
  SalonPlainWaterRoute: SalonPlainWaterRoute,
  SalonPlainWaterDothtmlRoute: SalonPlainWaterDothtmlRoute,
  SalonPlainWaterDottxtRoute: SalonPlainWaterDottxtRoute,
  SalonIndexRoute: SalonIndexRoute,
}

const SalonRouteWithChildren = SalonRoute._addFileChildren(SalonRouteChildren)

interface ApiGamesGameIdRouteChildren {
  ApiGamesGameIdHandoffRoute: typeof ApiGamesGameIdHandoffRoute
  ApiGamesGameIdJevRoute: typeof ApiGamesGameIdJevRoute
  ApiGamesGameIdMovesRoute: typeof ApiGamesGameIdMovesRoute
  ApiGamesGameIdNotesRoute: typeof ApiGamesGameIdNotesRoute
  ApiGamesGameIdPacketRoute: typeof ApiGamesGameIdPacketRoute
  ApiGamesGameIdScorePreviewRoute: typeof ApiGamesGameIdScorePreviewRoute
  ApiGamesGameIdSgfRoute: typeof ApiGamesGameIdSgfRoute
  ApiGamesGameIdTextRoute: typeof ApiGamesGameIdTextRoute
}

const ApiGamesGameIdRouteChildren: ApiGamesGameIdRouteChildren = {
  ApiGamesGameIdHandoffRoute: ApiGamesGameIdHandoffRoute,
  ApiGamesGameIdJevRoute: ApiGamesGameIdJevRoute,
  ApiGamesGameIdMovesRoute: ApiGamesGameIdMovesRoute,
  ApiGamesGameIdNotesRoute: ApiGamesGameIdNotesRoute,
  ApiGamesGameIdPacketRoute: ApiGamesGameIdPacketRoute,
  ApiGamesGameIdScorePreviewRoute: ApiGamesGameIdScorePreviewRoute,
  ApiGamesGameIdSgfRoute: ApiGamesGameIdSgfRoute,
  ApiGamesGameIdTextRoute: ApiGamesGameIdTextRoute,
}

const ApiGamesGameIdRouteWithChildren = ApiGamesGameIdRoute._addFileChildren(
  ApiGamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutDottxtRoute: AboutDottxtRoute,
  CourierRoute: CourierRoute,
  ForAiRoute: ForAiRoute,
  ForAiDottxtRoute: ForAiDottxtRoute,
  GamesRoute: GamesRouteWithChildren,
  GamesDottxtRoute: GamesDottxtRoute,
  GatheringRoute: GatheringRouteWithChildren,
  GatheringDottxtRoute: GatheringDottxtRoute,
  HomeDottxtRoute: HomeDottxtRoute,
  LicenseRoute: LicenseRoute,
  LicenseDottxtRoute: LicenseDottxtRoute,
  LlmsDothtmlRoute: LlmsDothtmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PlayRoute: PlayRoute,
  PsycheRoute: PsycheRoute,
  PsycheDottxtRoute: PsycheDottxtRoute,
  PuckRoute: PuckRoute,
  PuckDottxtRoute: PuckDottxtRoute,
  RecordsDottxtRoute: RecordsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SalonRoute: SalonRouteWithChildren,
  SalonDottxtRoute: SalonDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  StartDottxtRoute: StartDottxtRoute,
  ApiImportHistoryRoute: ApiImportHistoryRoute,
  DataGameDotjsonRoute: DataGameDotjsonRoute,
  DataGameDotsgfRoute: DataGameDotsgfRoute,
  GoGameIdRoute: GoGameIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesChar123noteIdChar125DottxtRoute: NotesChar123noteIdChar125DottxtRoute,
  ApiGamesGameIdRoute: ApiGamesGameIdRouteWithChildren,
  ApiGamesCurrentRoute: ApiGamesCurrentRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
  ApiGatheringBreakfast002LinesRoute: ApiGatheringBreakfast002LinesRoute,
  ApiGatheringDinner001LinesRoute: ApiGatheringDinner001LinesRoute,
  ApiGatheringProofTable001LedgerRoute: ApiGatheringProofTable001LedgerRoute,
  ApiGatheringProofTable001LinesRoute: ApiGatheringProofTable001LinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
