/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as ForAiRouteImport } from './routes/for-ai'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PuckRouteImport } from './routes/puck'
import { Route as StartRouteImport } from './routes/start'
import { Route as ApiImportHistoryRouteImport } from './routes/api/import-history'
import { Route as DataGameDotjsonRouteImport } from './routes/data/game[.]json'
import { Route as DataGameDotsgfRouteImport } from './routes/data/game[.]sgf'
import { Route as GamesIndexDotjsonRouteImport } from './routes/games/index[.]json'
import { Route as GoGameIdRouteImport } from './routes/go.$gameId'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as ApiGamesGameIdRouteImport } from './routes/api/games/$gameId'
import { Route as ApiGamesCurrentRouteImport } from './routes/api/games/current'
import { Route as ApiGamesGameIdHandoffRouteImport } from './routes/api/games/$gameId.handoff'
import { Route as ApiGamesGameIdJevRouteImport } from './routes/api/games/$gameId.jev'
import { Route as ApiGamesGameIdMovesRouteImport } from './routes/api/games/$gameId.moves'
import { Route as ApiGamesGameIdNotesRouteImport } from './routes/api/games/$gameId.notes'
import { Route as ApiGamesGameIdPacketRouteImport } from './routes/api/games/$gameId.packet'
import { Route as ApiGamesGameIdScorePreviewRouteImport } from './routes/api/games/$gameId.score-preview'
import { Route as ApiGamesGameIdSgfRouteImport } from './routes/api/games/$gameId.sgf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAiRoute = ForAiRouteImport.update({
  id: '/for-ai',
  path: '/for-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PuckRoute = PuckRouteImport.update({
  id: '/puck',
  path: '/puck',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportHistoryRoute = ApiImportHistoryRouteImport.update({
  id: '/api/import-history',
  path: '/api/import-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGameDotjsonRoute = DataGameDotjsonRouteImport.update({
  id: '/data/game.json',
  path: '/data/game.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGameDotsgfRoute = DataGameDotsgfRouteImport.update({
  id: '/data/game.sgf',
  path: '/data/game.sgf',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexDotjsonRoute = GamesIndexDotjsonRouteImport.update({
  id: '/index.json',
  path: '/index.json',
  getParentRoute: () => GamesRoute,
} as any)
const GoGameIdRoute = GoGameIdRouteImport.update({
  id: '/go/$gameId',
  path: '/go/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdRoute = ApiGamesGameIdRouteImport.update({
  id: '/api/games/$gameId',
  path: '/api/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCurrentRoute = ApiGamesCurrentRouteImport.update({
  id: '/api/games/current',
  path: '/api/games/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdHandoffRoute = ApiGamesGameIdHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdJevRoute = ApiGamesGameIdJevRouteImport.update({
  id: '/jev',
  path: '/jev',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdMovesRoute = ApiGamesGameIdMovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdNotesRoute = ApiGamesGameIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdPacketRoute = ApiGamesGameIdPacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdScorePreviewRoute =
  ApiGamesGameIdScorePreviewRouteImport.update({
    id: '/score-preview',
    path: '/score-preview',
    getParentRoute: () => ApiGamesGameIdRoute,
  } as any)
const ApiGamesGameIdSgfRoute = ApiGamesGameIdSgfRouteImport.update({
  id: '/sgf',
  path: '/sgf',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/games': typeof GamesRouteWithChildren
  '/license': typeof LicenseRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/puck': typeof PuckRoute
  '/start': typeof StartRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/games': typeof GamesRouteWithChildren
  '/license': typeof LicenseRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/puck': typeof PuckRoute
  '/start': typeof StartRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/games': typeof GamesRouteWithChildren
  '/license': typeof LicenseRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/puck': typeof PuckRoute
  '/start': typeof StartRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courier'
    | '/for-ai'
    | '/games'
    | '/license'
    | '/llms.txt'
    | '/play'
    | '/puck'
    | '/start'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/index.json'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/api/games/'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courier'
    | '/for-ai'
    | '/games'
    | '/license'
    | '/llms.txt'
    | '/play'
    | '/puck'
    | '/start'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/index.json'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/api/games'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courier'
    | '/for-ai'
    | '/games'
    | '/license'
    | '/llms.txt'
    | '/play'
    | '/puck'
    | '/start'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/index.json'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/api/games/'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CourierRoute: typeof CourierRoute
  ForAiRoute: typeof ForAiRoute
  GamesRoute: typeof GamesRouteWithChildren
  LicenseRoute: typeof LicenseRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PlayRoute: typeof PlayRoute
  PuckRoute: typeof PuckRoute
  StartRoute: typeof StartRoute
  ApiImportHistoryRoute: typeof ApiImportHistoryRoute
  DataGameDotjsonRoute: typeof DataGameDotjsonRoute
  DataGameDotsgfRoute: typeof DataGameDotsgfRoute
  GoGameIdRoute: typeof GoGameIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  ApiGamesGameIdRoute: typeof ApiGamesGameIdRouteWithChildren
  ApiGamesCurrentRoute: typeof ApiGamesCurrentRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-ai': {
      id: '/for-ai'
      path: '/for-ai'
      fullPath: '/for-ai'
      preLoaderRoute: typeof ForAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puck': {
      id: '/puck'
      path: '/puck'
      fullPath: '/puck'
      preLoaderRoute: typeof PuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-history': {
      id: '/api/import-history'
      path: '/api/import-history'
      fullPath: '/api/import-history'
      preLoaderRoute: typeof ApiImportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/game.json': {
      id: '/data/game.json'
      path: '/data/game.json'
      fullPath: '/data/game.json'
      preLoaderRoute: typeof DataGameDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/game.sgf': {
      id: '/data/game.sgf'
      path: '/data/game.sgf'
      fullPath: '/data/game.sgf'
      preLoaderRoute: typeof DataGameDotsgfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/index.json': {
      id: '/games/index.json'
      path: '/index.json'
      fullPath: '/games/index.json'
      preLoaderRoute: typeof GamesIndexDotjsonRouteImport
      parentRoute: typeof GamesRoute
    }
    '/go/$gameId': {
      id: '/go/$gameId'
      path: '/go/$gameId'
      fullPath: '/go/$gameId'
      preLoaderRoute: typeof GoGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games/'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId': {
      id: '/api/games/$gameId'
      path: '/api/games/$gameId'
      fullPath: '/api/games/$gameId'
      preLoaderRoute: typeof ApiGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/current': {
      id: '/api/games/current'
      path: '/api/games/current'
      fullPath: '/api/games/current'
      preLoaderRoute: typeof ApiGamesCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/handoff': {
      id: '/api/games/$gameId/handoff'
      path: '/handoff'
      fullPath: '/api/games/$gameId/handoff'
      preLoaderRoute: typeof ApiGamesGameIdHandoffRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/jev': {
      id: '/api/games/$gameId/jev'
      path: '/jev'
      fullPath: '/api/games/$gameId/jev'
      preLoaderRoute: typeof ApiGamesGameIdJevRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/moves': {
      id: '/api/games/$gameId/moves'
      path: '/moves'
      fullPath: '/api/games/$gameId/moves'
      preLoaderRoute: typeof ApiGamesGameIdMovesRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/notes': {
      id: '/api/games/$gameId/notes'
      path: '/notes'
      fullPath: '/api/games/$gameId/notes'
      preLoaderRoute: typeof ApiGamesGameIdNotesRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/packet': {
      id: '/api/games/$gameId/packet'
      path: '/packet'
      fullPath: '/api/games/$gameId/packet'
      preLoaderRoute: typeof ApiGamesGameIdPacketRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/score-preview': {
      id: '/api/games/$gameId/score-preview'
      path: '/score-preview'
      fullPath: '/api/games/$gameId/score-preview'
      preLoaderRoute: typeof ApiGamesGameIdScorePreviewRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/sgf': {
      id: '/api/games/$gameId/sgf'
      path: '/sgf'
      fullPath: '/api/games/$gameId/sgf'
      preLoaderRoute: typeof ApiGamesGameIdSgfRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
  }
}

interface GamesRouteChildren {
  GamesIndexDotjsonRoute: typeof GamesIndexDotjsonRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIndexDotjsonRoute: GamesIndexDotjsonRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface ApiGamesGameIdRouteChildren {
  ApiGamesGameIdHandoffRoute: typeof ApiGamesGameIdHandoffRoute
  ApiGamesGameIdJevRoute: typeof ApiGamesGameIdJevRoute
  ApiGamesGameIdMovesRoute: typeof ApiGamesGameIdMovesRoute
  ApiGamesGameIdNotesRoute: typeof ApiGamesGameIdNotesRoute
  ApiGamesGameIdPacketRoute: typeof ApiGamesGameIdPacketRoute
  ApiGamesGameIdScorePreviewRoute: typeof ApiGamesGameIdScorePreviewRoute
  ApiGamesGameIdSgfRoute: typeof ApiGamesGameIdSgfRoute
}

const ApiGamesGameIdRouteChildren: ApiGamesGameIdRouteChildren = {
  ApiGamesGameIdHandoffRoute: ApiGamesGameIdHandoffRoute,
  ApiGamesGameIdJevRoute: ApiGamesGameIdJevRoute,
  ApiGamesGameIdMovesRoute: ApiGamesGameIdMovesRoute,
  ApiGamesGameIdNotesRoute: ApiGamesGameIdNotesRoute,
  ApiGamesGameIdPacketRoute: ApiGamesGameIdPacketRoute,
  ApiGamesGameIdScorePreviewRoute: ApiGamesGameIdScorePreviewRoute,
  ApiGamesGameIdSgfRoute: ApiGamesGameIdSgfRoute,
}

const ApiGamesGameIdRouteWithChildren = ApiGamesGameIdRoute._addFileChildren(
  ApiGamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CourierRoute: CourierRoute,
  ForAiRoute: ForAiRoute,
  GamesRoute: GamesRouteWithChildren,
  LicenseRoute: LicenseRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PlayRoute: PlayRoute,
  PuckRoute: PuckRoute,
  StartRoute: StartRoute,
  ApiImportHistoryRoute: ApiImportHistoryRoute,
  DataGameDotjsonRoute: DataGameDotjsonRoute,
  DataGameDotsgfRoute: DataGameDotsgfRoute,
  GoGameIdRoute: GoGameIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  ApiGamesGameIdRoute: ApiGamesGameIdRouteWithChildren,
  ApiGamesCurrentRoute: ApiGamesCurrentRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
