/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as ForAiRouteImport } from './routes/for-ai'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GatheringRouteImport } from './routes/gathering'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LlmsDothtmlRouteImport } from './routes/llms[.]html'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PsycheRouteImport } from './routes/psyche'
import { Route as PuckRouteImport } from './routes/puck'
import { Route as RecordsDottxtRouteImport } from './routes/records[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SalonRouteImport } from './routes/salon'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartRouteImport } from './routes/start'
import { Route as ApiImportHistoryRouteImport } from './routes/api/import-history'
import { Route as DataGameDotjsonRouteImport } from './routes/data/game[.]json'
import { Route as DataGameDotsgfRouteImport } from './routes/data/game[.]sgf'
import { Route as GamesIndexDotjsonRouteImport } from './routes/games/index[.]json'
import { Route as GatheringDinner001IndexDothtmlRouteImport } from './routes/gathering/dinner-001-index[.]html'
import { Route as GatheringDinner001IndexDottxtRouteImport } from './routes/gathering/dinner-001-index[.]txt'
import { Route as GatheringDinner001DothtmlRouteImport } from './routes/gathering/dinner-001[.]html'
import { Route as GatheringDinner001DotjsonRouteImport } from './routes/gathering/dinner-001[.]json'
import { Route as GatheringDinner001DottxtRouteImport } from './routes/gathering/dinner-001[.]txt'
import { Route as GatheringIndexDothtmlRouteImport } from './routes/gathering/index[.]html'
import { Route as GoGameIdRouteImport } from './routes/go.$gameId'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as ApiGamesGameIdRouteImport } from './routes/api/games/$gameId'
import { Route as ApiGamesCurrentRouteImport } from './routes/api/games/current'
import { Route as GatheringDinner001PartPartDothtmlRouteImport } from './routes/gathering/dinner-001-part/$part[.]html'
import { Route as GatheringDinner001PartPartDottxtRouteImport } from './routes/gathering/dinner-001-part/$part[.]txt'
import { Route as GatheringDinner001IndexRouteImport } from './routes/gathering/dinner-001/index'
import { Route as ApiGamesGameIdHandoffRouteImport } from './routes/api/games/$gameId.handoff'
import { Route as ApiGamesGameIdJevRouteImport } from './routes/api/games/$gameId.jev'
import { Route as ApiGamesGameIdMovesRouteImport } from './routes/api/games/$gameId.moves'
import { Route as ApiGamesGameIdNotesRouteImport } from './routes/api/games/$gameId.notes'
import { Route as ApiGamesGameIdPacketRouteImport } from './routes/api/games/$gameId.packet'
import { Route as ApiGamesGameIdScorePreviewRouteImport } from './routes/api/games/$gameId.score-preview'
import { Route as ApiGamesGameIdSgfRouteImport } from './routes/api/games/$gameId.sgf'
import { Route as ApiGamesGameIdTextRouteImport } from './routes/api/games/$gameId.text'
import { Route as ApiGatheringDinner001LinesRouteImport } from './routes/api/gathering/dinner-001.lines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAiRoute = ForAiRouteImport.update({
  id: '/for-ai',
  path: '/for-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringRoute = GatheringRouteImport.update({
  id: '/gathering',
  path: '/gathering',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDothtmlRoute = LlmsDothtmlRouteImport.update({
  id: '/llms.html',
  path: '/llms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PsycheRoute = PsycheRouteImport.update({
  id: '/psyche',
  path: '/psyche',
  getParentRoute: () => rootRouteImport,
} as any)
const PuckRoute = PuckRouteImport.update({
  id: '/puck',
  path: '/puck',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsDottxtRoute = RecordsDottxtRouteImport.update({
  id: '/records.txt',
  path: '/records.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportHistoryRoute = ApiImportHistoryRouteImport.update({
  id: '/api/import-history',
  path: '/api/import-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGameDotjsonRoute = DataGameDotjsonRouteImport.update({
  id: '/data/game.json',
  path: '/data/game.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGameDotsgfRoute = DataGameDotsgfRouteImport.update({
  id: '/data/game.sgf',
  path: '/data/game.sgf',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexDotjsonRoute = GamesIndexDotjsonRouteImport.update({
  id: '/index.json',
  path: '/index.json',
  getParentRoute: () => GamesRoute,
} as any)
const GatheringDinner001IndexDothtmlRoute =
  GatheringDinner001IndexDothtmlRouteImport.update({
    id: '/dinner-001-index.html',
    path: '/dinner-001-index.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001IndexDottxtRoute =
  GatheringDinner001IndexDottxtRouteImport.update({
    id: '/dinner-001-index.txt',
    path: '/dinner-001-index.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001DothtmlRoute =
  GatheringDinner001DothtmlRouteImport.update({
    id: '/dinner-001.html',
    path: '/dinner-001.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001DotjsonRoute =
  GatheringDinner001DotjsonRouteImport.update({
    id: '/dinner-001.json',
    path: '/dinner-001.json',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001DottxtRoute =
  GatheringDinner001DottxtRouteImport.update({
    id: '/dinner-001.txt',
    path: '/dinner-001.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringIndexDothtmlRoute = GatheringIndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => GatheringRoute,
} as any)
const GoGameIdRoute = GoGameIdRouteImport.update({
  id: '/go/$gameId',
  path: '/go/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdRoute = ApiGamesGameIdRouteImport.update({
  id: '/api/games/$gameId',
  path: '/api/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCurrentRoute = ApiGamesCurrentRouteImport.update({
  id: '/api/games/current',
  path: '/api/games/current',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringDinner001PartPartDothtmlRoute =
  GatheringDinner001PartPartDothtmlRouteImport.update({
    id: '/dinner-001-part/$part.html',
    path: '/dinner-001-part/$part.html',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001PartPartDottxtRoute =
  GatheringDinner001PartPartDottxtRouteImport.update({
    id: '/dinner-001-part/$part.txt',
    path: '/dinner-001-part/$part.txt',
    getParentRoute: () => GatheringRoute,
  } as any)
const GatheringDinner001IndexRoute = GatheringDinner001IndexRouteImport.update({
  id: '/dinner-001/',
  path: '/dinner-001/',
  getParentRoute: () => GatheringRoute,
} as any)
const ApiGamesGameIdHandoffRoute = ApiGamesGameIdHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdJevRoute = ApiGamesGameIdJevRouteImport.update({
  id: '/jev',
  path: '/jev',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdMovesRoute = ApiGamesGameIdMovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdNotesRoute = ApiGamesGameIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdPacketRoute = ApiGamesGameIdPacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdScorePreviewRoute =
  ApiGamesGameIdScorePreviewRouteImport.update({
    id: '/score-preview',
    path: '/score-preview',
    getParentRoute: () => ApiGamesGameIdRoute,
  } as any)
const ApiGamesGameIdSgfRoute = ApiGamesGameIdSgfRouteImport.update({
  id: '/sgf',
  path: '/sgf',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGamesGameIdTextRoute = ApiGamesGameIdTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ApiGamesGameIdRoute,
} as any)
const ApiGatheringDinner001LinesRoute =
  ApiGatheringDinner001LinesRouteImport.update({
    id: '/api/gathering/dinner-001/lines',
    path: '/api/gathering/dinner-001/lines',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/games': typeof GamesRouteWithChildren
  '/gathering': typeof GatheringRouteWithChildren
  '/license': typeof LicenseRoute
  '/llms.html': typeof LlmsDothtmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/psyche': typeof PsycheRoute
  '/puck': typeof PuckRoute
  '/records.txt': typeof RecordsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salon': typeof SalonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/gathering/dinner-001-index.html': typeof GatheringDinner001IndexDothtmlRoute
  '/gathering/dinner-001-index.txt': typeof GatheringDinner001IndexDottxtRoute
  '/gathering/dinner-001.html': typeof GatheringDinner001DothtmlRoute
  '/gathering/dinner-001.json': typeof GatheringDinner001DotjsonRoute
  '/gathering/dinner-001.txt': typeof GatheringDinner001DottxtRoute
  '/gathering/index.html': typeof GatheringIndexDothtmlRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/gathering/dinner-001-part/$part.html': typeof GatheringDinner001PartPartDothtmlRoute
  '/gathering/dinner-001-part/$part.txt': typeof GatheringDinner001PartPartDottxtRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/gathering/dinner-001/': typeof GatheringDinner001IndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
  '/api/games/$gameId/text': typeof ApiGamesGameIdTextRoute
  '/api/gathering/dinner-001/lines': typeof ApiGatheringDinner001LinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/games': typeof GamesRouteWithChildren
  '/gathering': typeof GatheringRouteWithChildren
  '/license': typeof LicenseRoute
  '/llms.html': typeof LlmsDothtmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/psyche': typeof PsycheRoute
  '/puck': typeof PuckRoute
  '/records.txt': typeof RecordsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salon': typeof SalonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/gathering/dinner-001-index.html': typeof GatheringDinner001IndexDothtmlRoute
  '/gathering/dinner-001-index.txt': typeof GatheringDinner001IndexDottxtRoute
  '/gathering/dinner-001.html': typeof GatheringDinner001DothtmlRoute
  '/gathering/dinner-001.json': typeof GatheringDinner001DotjsonRoute
  '/gathering/dinner-001.txt': typeof GatheringDinner001DottxtRoute
  '/gathering/index.html': typeof GatheringIndexDothtmlRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/gathering/dinner-001-part/$part.html': typeof GatheringDinner001PartPartDothtmlRoute
  '/gathering/dinner-001-part/$part.txt': typeof GatheringDinner001PartPartDottxtRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/gathering/dinner-001': typeof GatheringDinner001IndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
  '/api/games/$gameId/text': typeof ApiGamesGameIdTextRoute
  '/api/gathering/dinner-001/lines': typeof ApiGatheringDinner001LinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courier': typeof CourierRoute
  '/for-ai': typeof ForAiRoute
  '/games': typeof GamesRouteWithChildren
  '/gathering': typeof GatheringRouteWithChildren
  '/license': typeof LicenseRoute
  '/llms.html': typeof LlmsDothtmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/play': typeof PlayRoute
  '/psyche': typeof PsycheRoute
  '/puck': typeof PuckRoute
  '/records.txt': typeof RecordsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salon': typeof SalonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/api/import-history': typeof ApiImportHistoryRoute
  '/data/game.json': typeof DataGameDotjsonRoute
  '/data/game.sgf': typeof DataGameDotsgfRoute
  '/games/index.json': typeof GamesIndexDotjsonRoute
  '/gathering/dinner-001-index.html': typeof GatheringDinner001IndexDothtmlRoute
  '/gathering/dinner-001-index.txt': typeof GatheringDinner001IndexDottxtRoute
  '/gathering/dinner-001.html': typeof GatheringDinner001DothtmlRoute
  '/gathering/dinner-001.json': typeof GatheringDinner001DotjsonRoute
  '/gathering/dinner-001.txt': typeof GatheringDinner001DottxtRoute
  '/gathering/index.html': typeof GatheringIndexDothtmlRoute
  '/go/$gameId': typeof GoGameIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRouteWithChildren
  '/api/games/current': typeof ApiGamesCurrentRoute
  '/gathering/dinner-001-part/$part.html': typeof GatheringDinner001PartPartDothtmlRoute
  '/gathering/dinner-001-part/$part.txt': typeof GatheringDinner001PartPartDottxtRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/gathering/dinner-001/': typeof GatheringDinner001IndexRoute
  '/api/games/$gameId/handoff': typeof ApiGamesGameIdHandoffRoute
  '/api/games/$gameId/jev': typeof ApiGamesGameIdJevRoute
  '/api/games/$gameId/moves': typeof ApiGamesGameIdMovesRoute
  '/api/games/$gameId/notes': typeof ApiGamesGameIdNotesRoute
  '/api/games/$gameId/packet': typeof ApiGamesGameIdPacketRoute
  '/api/games/$gameId/score-preview': typeof ApiGamesGameIdScorePreviewRoute
  '/api/games/$gameId/sgf': typeof ApiGamesGameIdSgfRoute
  '/api/games/$gameId/text': typeof ApiGamesGameIdTextRoute
  '/api/gathering/dinner-001/lines': typeof ApiGatheringDinner001LinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courier'
    | '/for-ai'
    | '/games'
    | '/gathering'
    | '/license'
    | '/llms.html'
    | '/llms.txt'
    | '/play'
    | '/psyche'
    | '/puck'
    | '/records.txt'
    | '/robots.txt'
    | '/salon'
    | '/sitemap.xml'
    | '/start'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/index.json'
    | '/gathering/dinner-001-index.html'
    | '/gathering/dinner-001-index.txt'
    | '/gathering/dinner-001.html'
    | '/gathering/dinner-001.json'
    | '/gathering/dinner-001.txt'
    | '/gathering/index.html'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/gathering/dinner-001-part/$part.html'
    | '/gathering/dinner-001-part/$part.txt'
    | '/api/games/'
    | '/gathering/dinner-001/'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
    | '/api/games/$gameId/text'
    | '/api/gathering/dinner-001/lines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courier'
    | '/for-ai'
    | '/games'
    | '/gathering'
    | '/license'
    | '/llms.html'
    | '/llms.txt'
    | '/play'
    | '/psyche'
    | '/puck'
    | '/records.txt'
    | '/robots.txt'
    | '/salon'
    | '/sitemap.xml'
    | '/start'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/index.json'
    | '/gathering/dinner-001-index.html'
    | '/gathering/dinner-001-index.txt'
    | '/gathering/dinner-001.html'
    | '/gathering/dinner-001.json'
    | '/gathering/dinner-001.txt'
    | '/gathering/index.html'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/gathering/dinner-001-part/$part.html'
    | '/gathering/dinner-001-part/$part.txt'
    | '/api/games'
    | '/gathering/dinner-001'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
    | '/api/games/$gameId/text'
    | '/api/gathering/dinner-001/lines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courier'
    | '/for-ai'
    | '/games'
    | '/gathering'
    | '/license'
    | '/llms.html'
    | '/llms.txt'
    | '/play'
    | '/psyche'
    | '/puck'
    | '/records.txt'
    | '/robots.txt'
    | '/salon'
    | '/sitemap.xml'
    | '/start'
    | '/api/import-history'
    | '/data/game.json'
    | '/data/game.sgf'
    | '/games/index.json'
    | '/gathering/dinner-001-index.html'
    | '/gathering/dinner-001-index.txt'
    | '/gathering/dinner-001.html'
    | '/gathering/dinner-001.json'
    | '/gathering/dinner-001.txt'
    | '/gathering/index.html'
    | '/go/$gameId'
    | '/notes/$noteId'
    | '/api/games/$gameId'
    | '/api/games/current'
    | '/gathering/dinner-001-part/$part.html'
    | '/gathering/dinner-001-part/$part.txt'
    | '/api/games/'
    | '/gathering/dinner-001/'
    | '/api/games/$gameId/handoff'
    | '/api/games/$gameId/jev'
    | '/api/games/$gameId/moves'
    | '/api/games/$gameId/notes'
    | '/api/games/$gameId/packet'
    | '/api/games/$gameId/score-preview'
    | '/api/games/$gameId/sgf'
    | '/api/games/$gameId/text'
    | '/api/gathering/dinner-001/lines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CourierRoute: typeof CourierRoute
  ForAiRoute: typeof ForAiRoute
  GamesRoute: typeof GamesRouteWithChildren
  GatheringRoute: typeof GatheringRouteWithChildren
  LicenseRoute: typeof LicenseRoute
  LlmsDothtmlRoute: typeof LlmsDothtmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PlayRoute: typeof PlayRoute
  PsycheRoute: typeof PsycheRoute
  PuckRoute: typeof PuckRoute
  RecordsDottxtRoute: typeof RecordsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SalonRoute: typeof SalonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  ApiImportHistoryRoute: typeof ApiImportHistoryRoute
  DataGameDotjsonRoute: typeof DataGameDotjsonRoute
  DataGameDotsgfRoute: typeof DataGameDotsgfRoute
  GoGameIdRoute: typeof GoGameIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  ApiGamesGameIdRoute: typeof ApiGamesGameIdRouteWithChildren
  ApiGamesCurrentRoute: typeof ApiGamesCurrentRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
  ApiGatheringDinner001LinesRoute: typeof ApiGatheringDinner001LinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-ai': {
      id: '/for-ai'
      path: '/for-ai'
      fullPath: '/for-ai'
      preLoaderRoute: typeof ForAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gathering': {
      id: '/gathering'
      path: '/gathering'
      fullPath: '/gathering'
      preLoaderRoute: typeof GatheringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.html': {
      id: '/llms.html'
      path: '/llms.html'
      fullPath: '/llms.html'
      preLoaderRoute: typeof LlmsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psyche': {
      id: '/psyche'
      path: '/psyche'
      fullPath: '/psyche'
      preLoaderRoute: typeof PsycheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puck': {
      id: '/puck'
      path: '/puck'
      fullPath: '/puck'
      preLoaderRoute: typeof PuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records.txt': {
      id: '/records.txt'
      path: '/records.txt'
      fullPath: '/records.txt'
      preLoaderRoute: typeof RecordsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-history': {
      id: '/api/import-history'
      path: '/api/import-history'
      fullPath: '/api/import-history'
      preLoaderRoute: typeof ApiImportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/game.json': {
      id: '/data/game.json'
      path: '/data/game.json'
      fullPath: '/data/game.json'
      preLoaderRoute: typeof DataGameDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/game.sgf': {
      id: '/data/game.sgf'
      path: '/data/game.sgf'
      fullPath: '/data/game.sgf'
      preLoaderRoute: typeof DataGameDotsgfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/index.json': {
      id: '/games/index.json'
      path: '/index.json'
      fullPath: '/games/index.json'
      preLoaderRoute: typeof GamesIndexDotjsonRouteImport
      parentRoute: typeof GamesRoute
    }
    '/gathering/dinner-001-index.html': {
      id: '/gathering/dinner-001-index.html'
      path: '/dinner-001-index.html'
      fullPath: '/gathering/dinner-001-index.html'
      preLoaderRoute: typeof GatheringDinner001IndexDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001-index.txt': {
      id: '/gathering/dinner-001-index.txt'
      path: '/dinner-001-index.txt'
      fullPath: '/gathering/dinner-001-index.txt'
      preLoaderRoute: typeof GatheringDinner001IndexDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001.html': {
      id: '/gathering/dinner-001.html'
      path: '/dinner-001.html'
      fullPath: '/gathering/dinner-001.html'
      preLoaderRoute: typeof GatheringDinner001DothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001.json': {
      id: '/gathering/dinner-001.json'
      path: '/dinner-001.json'
      fullPath: '/gathering/dinner-001.json'
      preLoaderRoute: typeof GatheringDinner001DotjsonRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001.txt': {
      id: '/gathering/dinner-001.txt'
      path: '/dinner-001.txt'
      fullPath: '/gathering/dinner-001.txt'
      preLoaderRoute: typeof GatheringDinner001DottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/index.html': {
      id: '/gathering/index.html'
      path: '/index.html'
      fullPath: '/gathering/index.html'
      preLoaderRoute: typeof GatheringIndexDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/go/$gameId': {
      id: '/go/$gameId'
      path: '/go/$gameId'
      fullPath: '/go/$gameId'
      preLoaderRoute: typeof GoGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games/'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId': {
      id: '/api/games/$gameId'
      path: '/api/games/$gameId'
      fullPath: '/api/games/$gameId'
      preLoaderRoute: typeof ApiGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/current': {
      id: '/api/games/current'
      path: '/api/games/current'
      fullPath: '/api/games/current'
      preLoaderRoute: typeof ApiGamesCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gathering/dinner-001-part/$part.html': {
      id: '/gathering/dinner-001-part/$part.html'
      path: '/dinner-001-part/$part.html'
      fullPath: '/gathering/dinner-001-part/$part.html'
      preLoaderRoute: typeof GatheringDinner001PartPartDothtmlRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001-part/$part.txt': {
      id: '/gathering/dinner-001-part/$part.txt'
      path: '/dinner-001-part/$part.txt'
      fullPath: '/gathering/dinner-001-part/$part.txt'
      preLoaderRoute: typeof GatheringDinner001PartPartDottxtRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/gathering/dinner-001/': {
      id: '/gathering/dinner-001/'
      path: '/dinner-001'
      fullPath: '/gathering/dinner-001/'
      preLoaderRoute: typeof GatheringDinner001IndexRouteImport
      parentRoute: typeof GatheringRoute
    }
    '/api/games/$gameId/handoff': {
      id: '/api/games/$gameId/handoff'
      path: '/handoff'
      fullPath: '/api/games/$gameId/handoff'
      preLoaderRoute: typeof ApiGamesGameIdHandoffRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/jev': {
      id: '/api/games/$gameId/jev'
      path: '/jev'
      fullPath: '/api/games/$gameId/jev'
      preLoaderRoute: typeof ApiGamesGameIdJevRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/moves': {
      id: '/api/games/$gameId/moves'
      path: '/moves'
      fullPath: '/api/games/$gameId/moves'
      preLoaderRoute: typeof ApiGamesGameIdMovesRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/notes': {
      id: '/api/games/$gameId/notes'
      path: '/notes'
      fullPath: '/api/games/$gameId/notes'
      preLoaderRoute: typeof ApiGamesGameIdNotesRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/packet': {
      id: '/api/games/$gameId/packet'
      path: '/packet'
      fullPath: '/api/games/$gameId/packet'
      preLoaderRoute: typeof ApiGamesGameIdPacketRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/score-preview': {
      id: '/api/games/$gameId/score-preview'
      path: '/score-preview'
      fullPath: '/api/games/$gameId/score-preview'
      preLoaderRoute: typeof ApiGamesGameIdScorePreviewRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/sgf': {
      id: '/api/games/$gameId/sgf'
      path: '/sgf'
      fullPath: '/api/games/$gameId/sgf'
      preLoaderRoute: typeof ApiGamesGameIdSgfRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/games/$gameId/text': {
      id: '/api/games/$gameId/text'
      path: '/text'
      fullPath: '/api/games/$gameId/text'
      preLoaderRoute: typeof ApiGamesGameIdTextRouteImport
      parentRoute: typeof ApiGamesGameIdRoute
    }
    '/api/gathering/dinner-001/lines': {
      id: '/api/gathering/dinner-001/lines'
      path: '/api/gathering/dinner-001/lines'
      fullPath: '/api/gathering/dinner-001/lines'
      preLoaderRoute: typeof ApiGatheringDinner001LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesIndexDotjsonRoute: typeof GamesIndexDotjsonRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIndexDotjsonRoute: GamesIndexDotjsonRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface GatheringRouteChildren {
  GatheringDinner001IndexDothtmlRoute: typeof GatheringDinner001IndexDothtmlRoute
  GatheringDinner001IndexDottxtRoute: typeof GatheringDinner001IndexDottxtRoute
  GatheringDinner001DothtmlRoute: typeof GatheringDinner001DothtmlRoute
  GatheringDinner001DotjsonRoute: typeof GatheringDinner001DotjsonRoute
  GatheringDinner001DottxtRoute: typeof GatheringDinner001DottxtRoute
  GatheringIndexDothtmlRoute: typeof GatheringIndexDothtmlRoute
  GatheringDinner001PartPartDothtmlRoute: typeof GatheringDinner001PartPartDothtmlRoute
  GatheringDinner001PartPartDottxtRoute: typeof GatheringDinner001PartPartDottxtRoute
  GatheringDinner001IndexRoute: typeof GatheringDinner001IndexRoute
}

const GatheringRouteChildren: GatheringRouteChildren = {
  GatheringDinner001IndexDothtmlRoute: GatheringDinner001IndexDothtmlRoute,
  GatheringDinner001IndexDottxtRoute: GatheringDinner001IndexDottxtRoute,
  GatheringDinner001DothtmlRoute: GatheringDinner001DothtmlRoute,
  GatheringDinner001DotjsonRoute: GatheringDinner001DotjsonRoute,
  GatheringDinner001DottxtRoute: GatheringDinner001DottxtRoute,
  GatheringIndexDothtmlRoute: GatheringIndexDothtmlRoute,
  GatheringDinner001PartPartDothtmlRoute:
    GatheringDinner001PartPartDothtmlRoute,
  GatheringDinner001PartPartDottxtRoute: GatheringDinner001PartPartDottxtRoute,
  GatheringDinner001IndexRoute: GatheringDinner001IndexRoute,
}

const GatheringRouteWithChildren = GatheringRoute._addFileChildren(
  GatheringRouteChildren,
)

interface ApiGamesGameIdRouteChildren {
  ApiGamesGameIdHandoffRoute: typeof ApiGamesGameIdHandoffRoute
  ApiGamesGameIdJevRoute: typeof ApiGamesGameIdJevRoute
  ApiGamesGameIdMovesRoute: typeof ApiGamesGameIdMovesRoute
  ApiGamesGameIdNotesRoute: typeof ApiGamesGameIdNotesRoute
  ApiGamesGameIdPacketRoute: typeof ApiGamesGameIdPacketRoute
  ApiGamesGameIdScorePreviewRoute: typeof ApiGamesGameIdScorePreviewRoute
  ApiGamesGameIdSgfRoute: typeof ApiGamesGameIdSgfRoute
  ApiGamesGameIdTextRoute: typeof ApiGamesGameIdTextRoute
}

const ApiGamesGameIdRouteChildren: ApiGamesGameIdRouteChildren = {
  ApiGamesGameIdHandoffRoute: ApiGamesGameIdHandoffRoute,
  ApiGamesGameIdJevRoute: ApiGamesGameIdJevRoute,
  ApiGamesGameIdMovesRoute: ApiGamesGameIdMovesRoute,
  ApiGamesGameIdNotesRoute: ApiGamesGameIdNotesRoute,
  ApiGamesGameIdPacketRoute: ApiGamesGameIdPacketRoute,
  ApiGamesGameIdScorePreviewRoute: ApiGamesGameIdScorePreviewRoute,
  ApiGamesGameIdSgfRoute: ApiGamesGameIdSgfRoute,
  ApiGamesGameIdTextRoute: ApiGamesGameIdTextRoute,
}

const ApiGamesGameIdRouteWithChildren = ApiGamesGameIdRoute._addFileChildren(
  ApiGamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CourierRoute: CourierRoute,
  ForAiRoute: ForAiRoute,
  GamesRoute: GamesRouteWithChildren,
  GatheringRoute: GatheringRouteWithChildren,
  LicenseRoute: LicenseRoute,
  LlmsDothtmlRoute: LlmsDothtmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PlayRoute: PlayRoute,
  PsycheRoute: PsycheRoute,
  PuckRoute: PuckRoute,
  RecordsDottxtRoute: RecordsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SalonRoute: SalonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  ApiImportHistoryRoute: ApiImportHistoryRoute,
  DataGameDotjsonRoute: DataGameDotjsonRoute,
  DataGameDotsgfRoute: DataGameDotsgfRoute,
  GoGameIdRoute: GoGameIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  ApiGamesGameIdRoute: ApiGamesGameIdRouteWithChildren,
  ApiGamesCurrentRoute: ApiGamesCurrentRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
  ApiGatheringDinner001LinesRoute: ApiGatheringDinner001LinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
